# Generated by Django 4.2 on 2023-06-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliweb', '0014_alter_service_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=500)),
                ('blog', models.TextField()),
                ('shortblog', models.CharField(max_length=250)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='.')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='blog',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='picture',
            field=models.ImageField(upload_to='.'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='picture',
            field=models.ImageField(upload_to='.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='picture',
            field=models.FileField(upload_to='.'),
        ),
    ]
