# Generated by Django 4.2 on 2023-06-08 13:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliweb', '0015_blog_portfolio_blog_portfolio_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='blog',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='about_me',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.DateField(),
        ),
    ]
