# Generated by Django 4.2 on 2023-06-14 05:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abduazim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
